logged_rules: ['sample', 'gibbs']

renumf90_path: '~/bin/renumf90'

gibbs_path: '/usr/local/bin/thrgibbs1f90'

post_gibbs_path: '/usr/local/bin/postgibbsf90'

iter: ['1', '2', '3', '4', '5']

sample_limit: "50000"

dataset: ['3v1', '3v2', '3v5', '3v7', '3v8', '3v9']

rounds: "500000"

burnin: "0"

thin: "20"

post_gibbs_burnin: "0"

#nohup echo -e 'renf90.par \n 500000 0 \n 20' | /usr/local/bin/thrgibbs1f90 &> gibbs.iter3.3v8.out &
