blupf90_path: "/usr/local/bin/blupf90"

renumf90_path: '~/bin/renumf90'

master_geno: 'data/raw_data/aaa50snp.dat'

master_map: 'data/raw_data/angus_map'

iter: ['1', '2', '3', '4', '5']

dataset: ['3v2', '3v7', '3v8']
