logged_rules: ['sample', 'aireml']

renumf90_path: '~/bin/renumf90'

airemlf90_path: '/usr/local/bin/airemlf90'

master_map: 'data/raw_data/angus_map'

master_geno: 'data/raw_data/aaa50snp.dat'

iter: ['1', '2', '3', '4', '5']

dataset: ['3v1', '3v2', '3v5', '3v7', '3v8', '3v9', 'all']

dataset_key: {'all':['all'], '3v1':['tworegion'], '3v2':['tworegion'], '3v5':['tworegion'], '3v7':['tworegion'], '3v8':['tworegion'], '3v9':['tworegion']}

resources_key: {'all':30, '3v1':20, '3v2':20, '3v5':20, '3v7':20, '3v8':20, '3v9':20}
