logged_rules: ['sample', 'gibbs']

renumf90_path: '~/bin/renumf90'

gibbs_path: '/usr/local/bin/gibbs2f90'

master_map: 'data/raw_data/angus_map'

master_geno: 'data/raw_data/aaa50snp.dat'

#iter: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

iter: ['1']

#dataset: ['all', '3v1', '3v2', '3v5', '3v7', '3v8', '3v9']

dataset: ['3v1', '3v2', '3v5', '3v7', '3v8', '3v9']

dataset_key: {'all':['all'], '3v1':['tworegion'], '3v2':['tworegion'], '3v5':['tworegion'], '3v7':['tworegion'], '3v8':['tworegion'], '3v9':['tworegion']}

burnin: 0

thin: 10

rounds: 20000
